---
- name: Install k8s and docker packages
  become: true
  hosts: k8s
  roles:
    - docker
    - k8s-all

- name: Setup master node
  become: true
  hosts: master
  roles:
    - k8s-master

- name: Setup worker node
  become: true
  hosts: worker
  roles:
    - k8s-worker

...