---
- name: Destroy cluster before starting again
  command: kubeadm reset -f

- name: Initialize k8s cluster
  command: kubeadm init
  register: kubeadm_init_output

- name: Create file with output
  copy:
    content: "{{ kubeadm_init_output.stdout }}"
    dest: /root/kubeadminit

- name: Prepare kubejoin script
  shell: tail -2 /root/kubeadminit > /root/kubejoin.sh

- name: Get kubejoin from k8s-master to ansible master
  fetch:
    src: /root/kubejoin.sh
    dest: ./join
    

- name: Organize files
  become: false
  shell: |
         cp join/{{ inventory_hostname }}/root/kubejoin.sh join/
         rm -fr join/{{ inventory_hostname }}
  delegate_to: localhost

- name: Install Pod network
  environment: 
    KUBECONFIG: /etc/kubernetes/admin.conf
  command: kubectl apply -f https://docs.projectcalico.org/v3.14/manifests/calico.yaml
    
...