docker_prereqs_packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common
- lsb-release
- gnupg 

docker_packages:
- docker-ce
- docker-ce-cli
#- containerd.io
